application:
  kinopoisk-api:
    host: localhost
    port: 8083
  bot:
    token:
    username:

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: cinema-bot
      port: 27017
      host: localhost